//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIMWebMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PIMResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PIMResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PIMWebMVC.Resources.PIMResource", typeof(PIMResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Criteria.
        /// </summary>
        public static string BTN_RESET_SEARCH {
            get {
                return ResourceManager.GetString("BTN_RESET_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BTN_SEARCH {
            get {
                return ResourceManager.GetString("BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission.
        /// </summary>
        public static string ERROR_ACCESS_DENIED_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_ACCESS_DENIED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string ERROR_ACCESS_DENIED_TITLE {
            get {
                return ResourceManager.GetString("ERROR_ACCESS_DENIED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is not valid.
        /// </summary>
        public static string ERROR_BAD_REQUEST_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_BAD_REQUEST_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        public static string ERROR_BAD_REQUEST_TITLE {
            get {
                return ResourceManager.GetString("ERROR_BAD_REQUEST_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOPS! - Could not Find it.
        /// </summary>
        public static string ERROR_NOT_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string ERROR_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("ERROR_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your administrator.
        /// </summary>
        public static string ERROR_SERVER_ERROR_PLEASE_CONTACT {
            get {
                return ResourceManager.GetString("ERROR_SERVER_ERROR_PLEASE_CONTACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string ERROR_SERVER_ERROR_TITLE {
            get {
                return ResourceManager.GetString("ERROR_SERVER_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occurred.
        /// </summary>
        public static string ERROR_SERVER_ERROR_UNEXPECTED_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_SERVER_ERROR_UNEXPECTED_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string LAYOUT_NAV_HELP {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LAYOUT_NAV_LOG_OUT {
            get {
                return ResourceManager.GetString("LAYOUT_NAV_LOG_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_ACCOUNT {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affair.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_AFFAIR {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_AFFAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_CUSTOMER {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_MY_PROJECTS {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_MY_PROJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_NEW {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_PROJECT {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_SEARCH {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string LAYOUT_SIDE_BAR_SUPPLIER {
            get {
                return ResourceManager.GetString("LAYOUT_SIDE_BAR_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Infomation Management.
        /// </summary>
        public static string LAYOUT_TITLE {
            get {
                return ResourceManager.GetString("LAYOUT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project number already existed. Please select a different project number.
        /// </summary>
        public static string MESSAGE_DUPLICATED_PROJECT_NUMBER {
            get {
                return ResourceManager.GetString("MESSAGE_DUPLICATED_PROJECT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must greater than start date.
        /// </summary>
        public static string MESSAGE_END_DATE_MUST_GREATER_THAN_START_DATE {
            get {
                return ResourceManager.GetString("MESSAGE_END_DATE_MUST_GREATER_THAN_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one criterion must be entered to search a project.
        /// </summary>
        public static string MESSAGE_INVALID_CRITERIA {
            get {
                return ResourceManager.GetString("MESSAGE_INVALID_CRITERIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all the mandatory fields (*)..
        /// </summary>
        public static string MESSAGE_MANDATORY_FIELD {
            get {
                return ResourceManager.GetString("MESSAGE_MANDATORY_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string PAGINATION_FIRST {
            get {
                return ResourceManager.GetString("PAGINATION_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string PAGINATION_LAST {
            get {
                return ResourceManager.GetString("PAGINATION_LAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PAGINATION_NEXT {
            get {
                return ResourceManager.GetString("PAGINATION_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PAGINATION_PREVIOUS {
            get {
                return ResourceManager.GetString("PAGINATION_PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string PROJECT_CREATE_MODE {
            get {
                return ResourceManager.GetString("PROJECT_CREATE_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string PROJECT_DETAILS_PAGE_TITLE {
            get {
                return ResourceManager.GetString("PROJECT_DETAILS_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string PROJECT_EDIT_MODE {
            get {
                return ResourceManager.GetString("PROJECT_EDIT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string PROJECT_LBL_CUSTOMER {
            get {
                return ResourceManager.GetString("PROJECT_LBL_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string PROJECT_LBL_END_DATE {
            get {
                return ResourceManager.GetString("PROJECT_LBL_END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PROJECT_LBL_NAME {
            get {
                return ResourceManager.GetString("PROJECT_LBL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string PROJECT_LBL_NUMBER {
            get {
                return ResourceManager.GetString("PROJECT_LBL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string PROJECT_LBL_START_DATE {
            get {
                return ResourceManager.GetString("PROJECT_LBL_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string PROJECT_LBL_STATUS {
            get {
                return ResourceManager.GetString("PROJECT_LBL_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Projects.
        /// </summary>
        public static string PROJECT_SEARCH_PAGE_TITLE {
            get {
                return ResourceManager.GetString("PROJECT_SEARCH_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string PROJECT_STATUS_FIN {
            get {
                return ResourceManager.GetString("PROJECT_STATUS_FIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Validated.
        /// </summary>
        public static string PROJECT_STATUS_INV {
            get {
                return ResourceManager.GetString("PROJECT_STATUS_INV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Validate.
        /// </summary>
        public static string PROJECT_STATUS_TOV {
            get {
                return ResourceManager.GetString("PROJECT_STATUS_TOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validated.
        /// </summary>
        public static string PROJECT_STATUS_VAL {
            get {
                return ResourceManager.GetString("PROJECT_STATUS_VAL", resourceCulture);
            }
        }
    }
}
